#!/usr/bin/env bash
# Usage: ./1-world_wide_web <domain> [<subdomain>]
# Display information about subdomains.

domain_information() {
    # Fetching information about the subdomain using dig
    line=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    
    # Printing formatted information about the subdomain
    echo "$2 $line" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

# Check the number of command-line arguments
if [ "$#" == 1 ]; then
    # If one argument is provided, display information for common subdomains
    domain_information "$1" "www"
    domain_information "$1" "lb-01"
    domain_information "$1" "web-01"
    domain_information "$1" "web-02"
elif [ "$#" == 2 ]; then
    # If two arguments are provided, display information for the specified subdomain
    domain_information "$1" "$2"
else
    # Display usage information if the number of arguments is incorrect
    echo "Usage: $0 <domain> [<subdomain>]"
    exit 1
fi
