#!/bin/bash

# transfer a file from a client to a server

if [ $# -lt 4 ]
then
	echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else

	PATH_TO_FILE=$1
	IP=$2
	USERNAME=$3
	PATH_TO_SSH_KEY=$4

	scp -o StrictHostKeyChecking=no "$PATH_TO_SSH_KEY" "$PATH_TO_FILE" "$USERNAME@$IP:~"
fi
