#!/usr/bin/env bash

#set up a custorm error page

sudo apt-get update
sudo apt-get install -y nginx
sudo echo "Hello World!" > /var/www/html/index.html

sudo echo "Ceci n'est pas une page" > /var/www/html/404.html

echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html
    location /redirect_me {
        return 301 https://autodesk.com/revit;
    }

    error_page 404 /404.html;
    location = /404.html{
        internal;
    }
}" > default
sudo mv -f default /etc/nginx/sites-available/default
sudo service nginx restart