#!/usr/bin/env bash
# This script configures a server web-02 to be identical to web-01

#install nginx
apt-get -y update
apt-get -y install nginx

# Create directories
mkdir -p /var/www/html
echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

printf %s "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm;

    add_header X-Served-By $HOSTNAME;

    server_name _;

    location /redirect_me {
        return https://autodesk/revit;
    }

    error_page 404 /404.html;
    location /404 {
        root /var/www/html;
        internal;
    }
}" > /etc/nginx/sites-available/default

