#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains
# a custom header
#
balancer="\
frontend www-frontend
	bind 0.0.0.0:80
	mode http
	default_backend www-backend
    
backend www-backend
	balance roundrobin
	server 276157-web-01 54.157.144.210:80 check
	server 276157-web-02 100.25.14.49:80 check
"
# Update packages
apt-get -y update

# Add HAProxy PPA
apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.4
apt-get -y update

# Install HAProxy
apt-get -y install haproxy
cp -a /etc/haproxy/haproxy.cfg{,.orig}
echo "$balancer" >> /etc/haproxy/haproxy.cfg
service haproxy restart
