#!/usr/bin/env bash
# Install and setup haproxy

apt-get install -y software-properties-common
add-apt-repository -y pps:vbernat/haproxy-1.8
apt-get -y update
apt-get install -y haproxy=1.8.\*

echo "ENABLED=1" > /etc/default/haproxy

# Listen to the servers
echo "
    listen load_balancer
    bind *:80
    mode http
    balance roundrobin
    option httpclose
    option forwardfor
    server 276157-web-01 54.173.41.135:80 check
    server 276157-web-01 18.208.120.167:80 check
    " >> /etc/haproxy/haproxy.cfg
service haproxy start
