#!/usr/bin/env bash
# Install and setup haproxy

apt install --no-install-recommends software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.4 -y
apt install -y haproxy=2.4.\*
apt update -y

echo "ENABLED=1" > /etc/default/haproxy

# Listen to web1 and web2 servers                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
echo "
   listen load_balancer
   bind *:80
   mode http
   balance roundrobin
   option httpclose
   option forwardfor
   server 17272-web-01 44.200.83.158:80 check
   server 17272-web-02 3.237.16.226:80 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start
