#!/usr/bin/env bash
# Remove the existing configuration
rm /etc/nginx/sites-enabled/default
# Configure Nginx to listen on port 80 for all active IPs
ls -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
# Restart nginx
service nginx restart
