#!/usr/bin/env bash
# Configure a Nginx server to listen to port 80

rm /etc/nginx/sites-enabled/default
ls -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
